---
- name: make a build dir
  file: state=directory name=/root/hdfs-datanode-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/hdfs-datanode-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/hdfs-datanode-dockerized/start.sh mode=0755

- name: build a Docker image for HDFS datanode
  command: docker build -t gitinsky/hdfs-datanode:0.1.2 --rm /root/hdfs-datanode-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/hdfs-datanode:latest --rm /root/hdfs-datanode-dockerized
